name: 🚀 Feature Request
description: Suggest new features or integrations
title: '[FEATURE] '
labels: ['feature', 'enhancement']
body:
  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: What new capability?
      placeholder: "Evidence tracking with enhanced security"
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why this feature?
      description: User need or system improvement?
      placeholder: "Users request enhanced evidence tracking capabilities"
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas
      description: APIs, libraries, rough approach?
      placeholder: "Integrate blockchain verification API"
